eureka:
  instance:
    prefer-ip-address: true
    appname: USER-SERVICE 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
